# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('urns', models.CharField(max_length=200)),
                ('fields', models.CharField(max_length=200)),
                ('blocked', models.BooleanField(default=False)),
                ('stopped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('query', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.IntegerField()),
                ('get_sync', models.BooleanField(default=False)),
                ('send_sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('folder', models.CharField(max_length=200, null=True)),
                ('broadcast', models.IntegerField(null=True)),
                ('urn', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('visibility', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('responded', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('exit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Run')),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Run'),
        ),
        migrations.AddField(
            model_name='email',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Group'),
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Group'),
        ),
    ]
