# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('urns', models.CharField(max_length=200)),
                ('groups', models.CharField(max_length=250)),
                ('fields', models.CharField(max_length=200)),
                ('blocked', models.BooleanField(default=False)),
                ('stopped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('broadcast', models.IntegerField(null=True)),
                ('urn', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('visibility', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Contact')),
            ],
        ),
    ]
