# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
