# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('folder', models.CharField(max_length=200, null=True)),
                ('broadcast', models.IntegerField(null=True)),
                ('urn', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('visibility', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.Contact')),
            ],
        ),
    ]
