# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fields',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
