# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('broadcast', models.IntegerField()),
                ('contact', models.CharField(max_length=200)),
                ('urn', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('visibility', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified_on',
            field=models.DateTimeField(null=True),
        ),
    ]
