# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_auto_20170516_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
