# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_value_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='time',
        ),
    ]
