# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_remove_value_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='broadcast',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
