# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0008_auto_20170611_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='value',
            name='node',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
