# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0010_value_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='node',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
