# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0016_auto_20170805_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sms_maama_enrollment_date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
